### ISSUE TITLE
Cannot run in dev mode

### ISSUE THREAD

**Issue by OhaaCompany** [mixim-cc/notes-fe#46]
### **After i installed necessary dependencies with pnpm, i ran it with pnpm dev and i get an error as below:**

 **⚠ Invalid next.config.js options detected: 
 ⚠     The value at .experimental has an unexpected property, appDir, which is not in the list of allowed properties (appDocumentPreloading, adjustFontFallbacks, adjustFontFallbacksWithSizeAdjust, allowedRevalidateHeaderKeys, amp, clientRouterFilter, clientRouterFilterRedirects, clientRouterFilterAllowedRate, cpus, memoryBasedWorkersCount, craCompat, caseSensitiveRoutes, useDeploymentId, useDeploymentIdServerActions, deploymentId, disableOptimizedLoading, disablePostcssPresetEnv, esmExternals, serverActions, serverActionsBodySizeLimit, extensionAlias, externalDir, externalMiddlewareRewritesResolve, fallbackNodePolyfills, fetchCacheKeyPrefix, forceSwcTransforms, fullySpecified, gzipSize, 
incrementalCacheHandlerPath, isrFlushToDisk, isrMemoryCacheSize, largePageDataBytes, manualClientBasePath, middlewarePrefetch, nextScriptWorkers, optimizeCss, optimisticClientCache, outputFileTracingRoot, outputFileTracingExcludes, 
outputFileTracingIgnores, outputFileTracingIncludes, ppr, proxyTimeout, serverComponentsExternalPackages, scrollRestoration, sharedPool, sri, strictNextHead, swcMinify, swcPlugins, swcTraceProfiling, urlImports, workerThreads, webVitalsAttribution, mdxRs, typedRoutes, webpackBuildWorker, turbo, optimizePackageImports, optimizeServerReact, instrumentationHook, turbotrace, logging, serverMinification, serverSourceMaps).
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
 ⚠ App router is available by default now, `experimental.appDir` option can be safely removed.
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: C:\Users\Acer\Desktop\notes-fe\node_modules\.pnpm\next-pwa@5.6.0_@babel+core@7.22.9_next@13.5.1_webpack@5.89.0\node_modules\next-pwa\register.js
> [PWA] Service worker: C:\Users\Acer\Desktop\notes-fe\public\sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Build in develop mode, cache and precache are mostly disabled. This means offline support is disabled, but you can continue developing other functions in service worker.**

### **after i executed _pnpm build_ i get another error as:**

 **⚠ Invalid next.config.js options detected: 
 ⚠     The value at .experimental has an unexpected property, appDir, which is not in the list of allowed properties (appDocumentPreloading, adjustFontFallbacks, adjustFontFallbacksWithSizeAdjust, allowedRevalidateHeaderKeys, amp, clientRouterFilter, clientRouterFilterRedirects, clientRouterFilterAllowedRate, cpus, memoryBasedWorkersCount, craCompat, caseSensitiveRoutes, useDeploymentId, useDeploymentIdServerActions, deploymentId, disableOptimizedLoading, disablePostcssPresetEnv, esmExternals, serverActions, serverActionsBodySizeLimit, extensionAlias, externalDir, externalMiddlewareRewritesResolve, fallbackNodePolyfills, fetchCacheKeyPrefix, forceSwcTransforms, fullySpecified, gzipSize, 
incrementalCacheHandlerPath, isrFlushToDisk, isrMemoryCacheSize, largePageDataBytes, manualClientBasePath, middlewarePrefetch, nextScriptWorkers, optimizeCss, optimisticClientCache, outputFileTracingRoot, outputFileTracingExcludes, 
outputFileTracingIgnores, outputFileTracingIncludes, ppr, proxyTimeout, serverComponentsExternalPackages, scrollRestoration, sharedPool, sri, strictNextHead, swcMinify, swcPlugins, swcTraceProfiling, urlImports, workerThreads, webVitalsAttribution, mdxRs, typedRoutes, webpackBuildWorker, turbo, optimizePackageImports, optimizeServerReact, instrumentationHook, turbotrace, logging, serverMinification, serverSourceMaps).
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
 ⚠ App router is available by default now, `experimental.appDir` option can be safely removed.
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: C:\Users\Acer\Desktop\notes-fe\node_modules\.pnpm\next-pwa@5.6.0_@babel+core@7.22.9_next@13.5.1_webpack@5.89.0\node_modules\next-pwa\register.js
> [PWA] Service worker: C:\Users\Acer\Desktop\notes-fe\public\sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
   Creating an optimized production build . ELIFECYCLE  Command failed with exit code 3221225477.**
   
   
   what should i do? how to resolve it?

**Comment by anzeal** [comment]
Its about App router. We previously used it as experimental flag. As its stable now. We'll remove it, thanks for the issue.

**Comment by anzeal** [comment]
Changes has been pushed to `dev` branch. commit: f52325ad955dbf3f58c7c93181346f66c252bb3b
It will later be merged with `main`
